### ISSUE TITLE
text content color

### ISSUE THREAD

**Issue by rcrooks** [adebiyial/nightingale#1]
Hi @adebiyial 
I really like this theme a lot - except for HTML. The fact that the color of text content is identical to that of attribute values and almost identical to the color of tag names makes visual parsing a bit difficult.

It would be great if you could give the text content color a little contrast at least from tag names.

Thanks for considering,
Robert

**Comment by adebiyial** [comment]
Thanks Robert. I'd look into that and make an update ASAP. I'd notify you before uploading it. 👍

**Comment by rcrooks** [comment]
Thank you!

**Comment by adebiyial** [comment]
Hey, @rcrooks Check this out. Does this work?

<img width="881" alt="nightingale-html" src="https://user-images.githubusercontent.com/18689106/96495824-4df46000-1240-11eb-8ccd-1a59dcbc0e45.png">

**Comment by rcrooks** [comment]
@adebiyial that looks great! Thanks!

**Comment by adebiyial** [comment]
🎊🎊🎊 It's live now. (You might need to reload before updating.)

Thank you for your help!

**Comment by adebiyial** [comment]
Hey, @rcrooks 

🎊🎊🎊 It's live now. (You might need to reload before updating.)

Thank you for your help!

**Comment by rcrooks** [comment]
Perfect - thanks for the quick update!
